### ISSUE TITLE
Tab completion looks weird on left hand side

### ISSUE THREAD

**Issue by lkastner** [fhinkel/InteractiveShell#17]
Currently the tabs are just tracked like any other command. So the left hand side gets a lot of `\t` which we probably don't want. It results in lines like
```
hel	de		t	;
```
which we would rather want to look like
```
help det;
```

**Comment by fhinkel** [comment]
Oops, yes.

**Comment by lkastner** [comment]
This should be fixed in the following [commit](https://github.com/fhinkel/InteractiveShell/commit/ce475d61d85c48d2a522d3e8266a61c2e02f453b). Needs testing, but this issue can be closed.

**Comment by lkastner** [comment]
A short comment: The logic for tracking the commands has changed. Previously we tracked whatever the user sent from the rhs to the math program. Now we track what the math program sends back. For example we send
```
loadP TAB "Polyhedra"
```
to M2, then M2 will echo
```
i1: loadPackage "Polyhedra"
```
back and we track `loadPackage "Polyhedra"`. This results in a minimal delay of tracking, but eliminates tabs, so it looks much nicer. So far it works for M2 and Singular as well.
